services:
  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
  users-service:
    build:
      context: ./services/UsersService
      dockerfile: Dockerfile
    container_name: users-service
    ports:
      - "8081:8080"
      #- "5001:80"
    environment:
      - MongoDBSettings__ConnectionString=${MONGO_CONN}
      - MongoDBSettings__DatabaseName=${MONGO_DB}
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      #- ./services/UsersService:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
    depends_on:
      - mongo-db

  tests:
    build:
      context: .
      dockerfile: tests/UsersService.Tests/Dockerfile
    container_name: users-service-tests
    profiles: ["ci", "test"]

volumes:
  mongo-data: {}